/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controladores.AgendaControl;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Tay
 */
public class Agenda extends javax.swing.JFrame {
    
    private final AgendaControl control;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        control = new AgendaControl(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabAgendamento = new javax.swing.JTable();
        BotaoAgendar = new javax.swing.JToggleButton();
        ScrollObs = new javax.swing.JScrollPane();
        TextObs = new javax.swing.JTextArea();
        ComboServico = new javax.swing.JComboBox<>();
        ComboCliente = new javax.swing.JComboBox<>();
        TextHora = new javax.swing.JTextField();
        TextData = new javax.swing.JTextField();
        TextValor = new javax.swing.JTextField();
        TextID = new javax.swing.JTextField();
        Obs = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Data = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Servico = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        frameAgenda = new javax.swing.JLabel();
        fundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabAgendamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 830, 210));

        BotaoAgendar.setBackground(new java.awt.Color(168, 113, 5));
        BotaoAgendar.setFont(new java.awt.Font("Por Siempre Gótica", 0, 24)); // NOI18N
        BotaoAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAgendar.setText("Agendar");
        BotaoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 430, 40));

        TextObs.setColumns(20);
        TextObs.setRows(5);
        ScrollObs.setViewportView(TextObs);

        getContentPane().add(ScrollObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 430, 120));

        ComboServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 240, 30));

        ComboCliente.setToolTipText("");
        ComboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboClienteActionPerformed(evt);
            }
        });
        getContentPane().add(ComboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, 30));

        TextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(TextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 240, 30));

        TextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 240, 30));

        TextValor.setText("0");
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 240, 30));

        TextID.setText("0");
        TextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDActionPerformed(evt);
            }
        });
        getContentPane().add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 240, 30));

        Obs.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Obs.setForeground(new java.awt.Color(255, 255, 255));
        Obs.setText("Observação");
        getContentPane().add(Obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, 50));

        Hora.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 60, 30));

        Data.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 30));

        Valor.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor R$");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        Servico.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Servico.setForeground(new java.awt.Color(255, 255, 255));
        Servico.setText("Serviço");
        getContentPane().add(Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 50, 30));

        Cliente.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cliente");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 30));

        id.setFont(new java.awt.Font("Por Siempre Gótica", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Codigo");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 50, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Por Siempre Gótica", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 130, -1));

        frameAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(frameAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 1010, 520));

        fundoAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tay\\Desktop\\ProjetoLP3\\utensílios-de-salão-de-beleza.jpg")); // NOI18N
        getContentPane().add(fundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void TextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDActionPerformed

    private void ComboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboClienteActionPerformed

    private void TextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataActionPerformed

    private void TextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHoraActionPerformed

    private void BotaoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarActionPerformed
       this.control.agendar();
    }//GEN-LAST:event_BotaoAgendarActionPerformed

    private void ComboServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboServicoItemStateChanged
        this.control.attValor();
    }//GEN-LAST:event_ComboServicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoAgendar;
    private javax.swing.JLabel Cliente;
    private javax.swing.JComboBox<String> ComboCliente;
    private javax.swing.JComboBox<String> ComboServico;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Obs;
    private javax.swing.JScrollPane ScrollObs;
    private javax.swing.JLabel Servico;
    private javax.swing.JTable TabAgendamento;
    private javax.swing.JTextField TextData;
    private javax.swing.JTextField TextHora;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextArea TextObs;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel frameAgenda;
    private javax.swing.JLabel fundoAgenda;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.control.attTabela();
        this.control.attCliente();
        this.control.attServico();
        this.control.attValor();
        
    }
    
    public JComboBox<String> getComboCliente() {
        return ComboCliente;
    }

    public void setComboCliente(JComboBox<String> ComboCliente) {
        this.ComboCliente = ComboCliente;
    }

    public JComboBox<String> getComboServico() {
        return ComboServico;
    }

    public void setComboServico(JComboBox<String> ComboServico) {
        this.ComboServico = ComboServico;
    }

    public JTable getTabAgendamento() {
        return TabAgendamento;
    }

    public void setTabAgendamento(JTable TabAgendamento) {
        this.TabAgendamento = TabAgendamento;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTextData() {
        return TextData;
    }

    public void setTextData(JTextField TextData) {
        this.TextData = TextData;
    }

    public JTextField getTextHora() {
        return TextHora;
    }

    public void setTextHora(JTextField TextHora) {
        this.TextHora = TextHora;
    }

    public JTextField getTextID() {
        return TextID;
    }

    public void setTextID(JTextField TextID) {
        this.TextID = TextID;
    }

    public JTextArea getTextObs() {
        return TextObs;
    }

    public void setTextObs(JTextArea TextObs) {
        this.TextObs = TextObs;
    }
    
    
   
    
}
